#!/usr/bin/env python3
"""Replace Russian markdown headings with English equivalents."""

from __future__ import annotations

import re
import sys
from pathlib import Path

KB = Path(__file__).resolve().parents[1]

HEADING_LINE = re.compile(r"^(#{1,6}\s+)(.+)$")
CYRILLIC = re.compile(r"[а-яА-ЯёЁ]")

SKIP_DIRS = {".git", "reference/curated"}

REPLACEMENTS: dict[str, str] = {
    "## Ключевые понятия": "## Key concepts",
    "## Ссылки": "## Links",
    "## Карточки знаний (Q&A)": "## Interview Q&A (Knowledge cards)",
    "## Карточки знаний (роадмап / drill)": "## Interview Q&A (roadmap / drill)",
    "## Материалы": "## Materials",
    "## Ресурсы": "## Resources",
    "## Артефакты": "## Artifacts",
    "## Код и примеры": "## Code & examples",
    "## Структура топика": "## Topic structure",
    "## Структура топики (фактическая)": "## Topic structure (actual)",
    "## Источник": "## Source",
    "### Последние заметки": "### Recent notes",
    "## Как отвечать на интервью": "## How to answer in interviews",
    "## Паттерны": "## Patterns",
    "## Связь с базой": "## Link to parent topic",
    "## Связь с этим репозиторием": "## Link to this repository",
    "## Ключевые идеи": "## Key ideas",
    "## Что добавить после paste": "## TODO after paste",
    "## Что добавить в README после paste": "## TODO for parent README after paste",
    "## Концепты": "## Concepts",
    "## Поток данных": "## Data flow",
    "## Полезные модификаторы": "## Useful modifiers",
    "## Архитектура": "## Architecture",
    "## Глоссарий ключевых терминов": "## Glossary of key terms",
    "## 🎯 Фокус vs можно отложить (вопрос → ответ)": "## 🎯 Focus vs Defer",
    "## 🎯 Фокус vs можно отложить": "## 🎯 Focus vs Defer",
    "### Фокус": "### Focus",
    "### Отложить": "### Defer",
    "### Можно отложить": "### Defer",
    "## 📚 Что учить по уровням": "## 📚 What to learn by level",
    "## 📚 Ключевые термины (вопрос → ответ)": "## 📚 Key terms (question → answer)",
    "## 🏋️ Упражнения (10)": "## 🏋️ Exercises (10)",
    "## 🏋️ Упражнения (10) — обязательная практика": "## 🏋️ Exercises (10) — required practice",
    "## 🏋️ Упражнения (8) — обязательная практика": "## 🏋️ Exercises (8) — required practice",
    "## 🏋️ Упражнения (8)": "## 🏋️ Exercises (8)",
    "## 🏋️ Упражнения (12) — что должно получиться": "## 🏋️ Exercises (12) — expected outcomes",
    "## 🏋️ Упражнения (8) — что должно получиться": "## 🏋️ Exercises (8) — expected outcomes",
    "## Упражнения (10)": "## Exercises (10)",
    "## Практические выводы / что брать в работу": "## Practical takeaways",
    "## Мини-чеклист": "## Mini checklist",
    "## Мини-чеклист перед merge": "## Mini checklist before merge",
    "## Мини-чеклист перед генерацией SwiftUI-экрана": "## Mini checklist before generating a SwiftUI screen",
    "## Мини-чеклист для AI-сгенерированных тестов": "## Mini checklist for AI-generated tests",
    "## Что брать в работу": "## What to adopt",
    "## Что взять в практику (actionable)": "## Actionable takeaways",
    "## Приоритет для AI Product Engineering": "## Priority for AI Product Engineering",
    "## Карта темы (iOS)": "## Topic map (iOS)",
    "## Вопросы–ответы (собес)": "## Interview Q&A",
    "## Вопросы–ответы (собес / самопроверка)": "## Interview Q&A (self-check)",
    "## Официально": "## Official docs",
    "## Читать дальше": "## Read next",
    "## Что читать дальше": "## Read next",
    "## Что читать дальше (официально)": "## Read next (official)",
    "## Связанное": "## Related",
    "## Зачем": "## Why",
    "## Сравнение": "## Comparison",
    "## Зачем знать жизненный цикл": "## Why know the lifecycle",
    "## Зачем вообще нужны тесты": "## Why tests matter",
    "## Поток изменений": "## Change flow",
    "## Поток: schedule → context → view": "## Flow: schedule → context → view",
    "## Поток: view → VM → сеть": "## Flow: view → VM → network",
    "## Проблема Core Data в SwiftUI": "## Core Data problem in SwiftUI",
    "## CDE: границы capability": "## CDE: capability boundaries",
    "## Источники изменений и точность": "## Change sources and precision",
    "## Когда что на собесе": "## What to use when (interview)",
    "## Что такое SQLite?": "## What is SQLite?",
    "## Что такое NoSQL?": "## What is NoSQL?",
    "### Характеристики": "### Characteristics",
    "### Пример": "### Example",
    "### Типичные iOS use cases": "### Typical iOS use cases",
    "### Библиотеки поверх SQLite": "### Libraries on top of SQLite",
    "### Плюсы и минусы": "### Pros and cons",
    "### Типы NoSQL": "### NoSQL types",
    "### Пример document": "### Document example",
    "### Типичные use cases": "### Typical use cases",
    "### Что быстрее?": "### Which is faster?",
    "## Пример: social network": "## Example: social network",
    "## Где Core Data и SwiftData?": "## Where do Core Data and SwiftData fit?",
    "### Core Data — плюсы и минусы": "### Core Data — pros and cons",
    "### SwiftData — плюсы и минусы": "### SwiftData — pros and cons",
    "## Когда что использовать?": "## When to use what?",
    "## Типичная iOS-архитектура": "## Typical iOS architecture",
    "### Для iOS-разработчика": "### For iOS developers",
    "## Четыре стиля RPC": "## Four RPC styles",
    "## Setup в Xcode (клиент)": "## Setup in Xcode (client)",
    "## Lifecycle клиента": "## Client lifecycle",
    "## Protobuf на wire": "## Protobuf on the wire",
    "## Production (упомянуто в сессии, не в demo)": "## Production (mentioned in session, not in demo)",
    "## Deploy сервера (кратко)": "## Server deploy (brief)",
    "### Память и модель данных": "### Memory and data model",
    "### Типы и протоколы": "### Types and protocols",
    "### Синтаксис Swift / DSL": "### Swift syntax / DSL",
    "### Сеть и хранение": "### Network and storage",
    "### Метрики, диагностика и тесты": "### Metrics, diagnostics, and tests",
    "### Сборка и архитектура проекта": "### Build and project architecture",
    "### Процессы и документы": "### Processes and documents",
    "## Формулировки для собеса": "## Interview phrasing",
    "## Диаграммы": "## Diagrams",
    "## О чем статья": "## What the article covers",
    "## 11 уроков из статьи": "## 11 lessons from the article",
    "## Проблема, которую решает skill": "## Problem the skill solves",
    "## Почему skill лучше правил в одном большом AGENTS.md": "## Why a skill beats one large AGENTS.md",
    "## Какие правила особенно ценны для SwiftUI": "## Rules especially valuable for SwiftUI",
    "## Что это меняет в ежедневной разработке": "## What changes in day-to-day development",
    "## Что смотреть в репозитории в первую очередь": "## What to read first in the repo",
    "## В чём проблема “обычной” AI-генерации тестов": "## Problem with “ordinary” AI-generated tests",
    "## Что меняет Testing Skill": "## What Testing Skill changes",
    "## Какие практики особенно важны": "## Especially important practices",
    "## Что это даёт в ежедневной разработке": "## What it gives in daily development",
    "## Почему тема всё ещё актуальна": "## Why the topic is still relevant",
    "## Какие проблемы skill помогает закрыть": "## Problems the skill helps close",
    "## Как это помогает в ежедневной работе": "## How it helps in daily work",
    "## Центральная идея статьи": "## Central idea of the article",
    "## Как выглядит рабочий pipeline": "## What a working pipeline looks like",
    "## Что реально даёт прирост": "## What actually improves results",
    "## Честная часть: почему “с нуля” сначала не работает": "## Honest part: why “from scratch” fails at first",
    "## Что это значит для команды": "## What it means for the team",
    "## Зачем `Map` в SwiftUI": "## Why `Map` in SwiftUI",
    "## Основные строительные блоки": "## Main building blocks",
    "### 1) Состояние карты": "### 1) Map state",
    "### 2) Контент карты": "### 2) Map content",
    "### 3) Поиск и геокодирование": "### 3) Search and geocoding",
    "## Что изменилось в новой волне API (WWDC 2025)": "## What changed in the new API wave (WWDC 2025)",
    "## Частая ошибка в SwiftUI-картах": "## Common SwiftUI Maps mistake",
    "## Что такое `@Observable` и зачем он нужен": "## What `@Observable` is and why it matters",
    "## Какие проблемы он реально решает": "## Problems it actually solves",
    "## Подводные камни миграции": "## Migration pitfalls",
    "### 1) Поддержка iOS ниже 17": "### 1) iOS below 17 support",
    "### 2) Неоднородная архитектура во время перехода": "### 2) Mixed architecture during transition",
    "### 3) Механическая миграция без ревью": "### 3) Mechanical migration without review",
    "## Безопасный план миграции (по шагам)": "## Safe migration plan (step by step)",
    "## Почему нужен toast, если уже есть alert и sheet": "## Why toast when alert and sheet exist",
    "## Базовая архитектура toast в SwiftUI": "## Basic toast architecture in SwiftUI",
    "### 1) Модель уведомления": "### 1) Notification model",
    "### 2) Отдельный ToastView": "### 2) Dedicated ToastView",
    "### 3) ViewModifier или extension": "### 3) ViewModifier or extension",
    "### 4) Управление временем жизни": "### 4) Lifetime management",
    "### 5) Анимация и позиционирование": "### 5) Animation and positioning",
    "## На что обратить внимание в реальном проекте": "## What to watch in a real project",
    "### Обратная передача данных (аналог unwind segue)": "### Passing data back (unwind segue analogue)",
    "### Observation framework (`@Observable`) — что это и зачем": "### Observation framework (`@Observable`) — what and why",
    "## Конспект: Reflection с Mirror": "## Notes: Reflection with Mirror",
    "### Что такое reflection": "### What reflection is",
    "### Ограничения (важно для собеса)": "### Limits (important for interviews)",
    "### Практика: generic prettyPrint": "### Practice: generic prettyPrint",
    "### Что Mirror не показывает": "### What Mirror does not show",
    "## Конспект: @dynamicMemberLookup": "## Notes: @dynamicMemberLookup",
    "### Механизм": "### Mechanism",
    "### Антипаттерны": "### Anti-patterns",
    "### Родственные механизмы": "### Related mechanisms",
    "## Когда брать этот расклад": "## When to use this layout",
    "## Граф слоёв": "## Layer graph",
    "## Что лежит в каждом пакете": "## What lives in each package",
    "## Package.swift (идея)": "## Package.swift (idea)",
    "## ServiceEnvironment (массовая инъекция)": "## ServiceEnvironment (bulk injection)",
    "## Порядок миграции (legacy)": "## Migration order (legacy)",
    "## Что это даёт": "## What you gain",
    "## Trade-offs (честно)": "## Trade-offs (honest)",
    "## Устная заготовка (30 сек)": "## Oral summary (30 sec)",
    "### 1) Базовый List": "### 1) Basic List",
    "### 2) Identifiable-модели": "### 2) Identifiable models",
    "### 3) Секции": "### 3) Sections",
    "### 6) Кастомная строка": "### 6) Custom row",
    "### 1) Базовый API": "### 1) Basic API",
    "### 2) Встроенные расписания": "### 2) Built-in schedules",
    "### 4) Анимация без state": "### 4) Animation without state",
    "### 1) Почему `.onAppear` — ловушка для API": "### 1) Why `.onAppear` is an API trap",
    "### 2) Конечный автомат (`LoadState`)": "### 2) State machine (`LoadState`)",
    "### 4) Почему `.task`, а не `.onAppear`": "### 4) Why `.task`, not `.onAppear`",
    "### 5) Кооперативная отмена": "### 5) Cooperative cancellation",
    "## `.onAppear` vs `.task` — сводка": "## `.onAppear` vs `.task` — summary",
    "### Три entry points": "### Three entry points",
    "### SwiftUI: не делай так в `body`": "### SwiftUI: do not do this in `body`",
    "## Базовая модель": "## Basic model",
    "## Когда использовать": "## When to use",
    "## Частые ошибки": "## Common mistakes",
    "## Практические правила": "## Practical rules",
    "## Мини-пример": "## Mini example",
    "## Почему это важно в архитектуре": "## Why it matters in architecture",
    "## Почему возникает проблема": "## Why the problem arises",
    "## Что даёт `@isolated(any)` (SE-0431)": "## What `@isolated(any)` gives (SE-0431)",
    "## Что даёт `#isolation` (SE-0420)": "## What `#isolation` gives (SE-0420)",
    "## Где это особенно полезно": "## Where it is especially useful",
    "## Вводный конспект Swift Concurrency": "## Intro notes: Swift Concurrency",
    "## 1. Зачем это приложению": "## 1. Why the app needs this",
    "## 2. Синхронный код vs асинхронный": "## 2. Synchronous vs asynchronous code",
    "## 3. `Task` — единица асинхронной работы": "## 3. `Task` — unit of async work",
    "### 3.1. Что такое «context» в вопросе про `Task` vs `Task.detached`": "### 3.1. What “context” means for `Task` vs `Task.detached`",
    "## 4. Actor и изоляция (**actor isolation**)": "## 4. Actor and isolation (**actor isolation**)",
    "## 7. Отмена (**cancellation**)": "## 7. Cancellation",
    "## 8. `async let` и `TaskGroup` (очень кратко)": "## 8. `async let` and `TaskGroup` (very brief)",
    "## 10. Частые заблуждения": "## 10. Common misconceptions",
    "## 11. Карта: вводный конспект → Q11–Q20": "## 11. Map: intro notes → Q11–Q20",
    "## 12. Дальше по плану": "## 12. Next in the plan",
    "## Распространённость на рынке (ориентир для собеса)": "## Market prevalence (interview guide)",
    "### Краткие описания (конспект)": "### Brief descriptions (notes)",
    "#### MVVM (~41%) — лидер": "#### MVVM (~41%) — leader",
    "#### MVC (~34%) — второе место (часто legacy)": "#### MVC (~34%) — second place (often legacy)",
    "#### VIPER + Clean (~18%) — enterprise / тяжёлые модули": "#### VIPER + Clean (~18%) — enterprise / heavy modules",
    "#### TCA (~5%) — ниша": "#### TCA (~5%) — niche",
    "### Устная заготовка (30 сек, с цифрами)": "### Oral summary (30 sec, with numbers)",
    "## Почему монолит тормозит команду": "## Why a monolith slows the team",
    "### Цель модульности": "### Goal of modularization",
    "## Предлагаемая структура модулей": "## Proposed module structure",
    "## Ключевые правила зависимостей": "## Key dependency rules",
    "## Миграция legacy-монолита: практический порядок": "## Legacy monolith migration: practical order",
    "## Что такое throughput в контексте iOS": "## What throughput means on iOS",
    "## Базовые решения, которые нельзя пропускать": "## Baseline solutions you cannot skip",
    "### Проблема": "### Problem",
    "### Идея": "### Idea",
    "### Практический смысл": "### Practical meaning",
    "## Что это значит для архитектуры": "## What it means for architecture",
    "## Проблема при миграции с XCTest": "## Problem when migrating from XCTest",
    "## Идея: тестировать не callback, а поток событий": "## Idea: test event stream, not callback",
    "## Базовый шаблон": "## Basic template",
    "## Удобные extension для AsyncSequence": "## Handy AsyncSequence extensions",
    "## Поэтапная валидация (phase-based)": "## Phased validation",
    "## Семь стадий": "## Seven stages",
    "## Configuration: три типа": "## Configuration: three types",
    "## Тип задачи": "## Task type",
    "## State machine задачи": "## Task state machine",
    "## Network I/O и метрики": "## Network I/O and metrics",
    "## Response и кэш": "## Response and cache",
    "## Complete: URLError и retry": "## Complete: URLError and retry",
    "## Delegates (каскад)": "## Delegates (cascade)",
    "## Прогресс": "## Progress",
    "## Production checklist (сжатый)": "## Production checklist (compact)",
    "## Дерево решений (из статьи)": "## Decision tree (from article)",
    "## Подводные камни (top)": "## Top pitfalls",
    "## Apple docs (первичный источник)": "## Apple docs (primary source)",
    "### Границы и типичные ошибки": "### Boundaries and typical mistakes",
    "### Зачем логирование в system design interview": "### Why logging in a system design interview",
    "### Уровни, категории, PII": "### Levels, categories, PII",
    "### Связь с observability": "### Link to observability",
    "### API contract и versioning": "### API contract and versioning",
    "### Renderer на клиенте": "### Client renderer",
    "## 1. Определение флагов": "## 1. Flag definitions",
    "## 2. Источники и приоритеты": "## 2. Sources and priorities",
    "## 3. Resolver и thread safety": "## 3. Resolver and thread safety",
    "## 4. DSL для конфигурации": "## 4. DSL for configuration",
    "## 7. Remote config как source": "## 7. Remote config as source",
    "## Оглавление": "## Table of contents",
    "## Главная мысль": "## Main idea",
    "## Главный вопрос": "## Core question",
    "## Три способа запустить concurrent-работу": "## Three ways to start concurrent work",
    "## Граф зависимостей": "## Dependency graph",
    "## Правило большого пальца": "## Rule of thumb",
    "## Устные заготовки (собес)": "## Oral summaries (interview)",
    "## Шпаргалка одной строкой": "## One-line cheat sheet",
    "## Чего нет в посте (см. основной README и другие материалы)": "## Not in the post (see main README and other materials)",
    "## Связь с roadmap": "## Link to roadmap",
    "## Практики": "## Practices",
    "## Шаблон промпта: refactor тестов": "## Prompt template: refactor tests",
    "## Чем это не является": "## What it is not",
    "## Когда Swift Testing": "## When Swift Testing",
    "## Когда оставить XCTest": "## When to keep XCTest",
    "## Миграция с XCTestExpectation": "## Migration from XCTestExpectation",
    "## `@Suite` и изоляция": "## `@Suite` and isolation",
    "## Тестирование ViewModel / `@Observable`": "## Testing ViewModel / `@Observable`",
    "## Сосуществование в проекте": "## Coexistence in the project",
    "## Когда да / когда нет": "## When yes / when no",
    "## Дисциплина эталонов": "## Baseline discipline",
    "## Место в пирамиде": "## Place in the pyramid",
    "## Сторонние библиотеки": "## Third-party libraries",
    "## Уровни зрелости": "## Maturity levels",
    "## Fixture-based contract (минимум)": "## Fixture-based contract (minimum)",
    "## OpenAPI как source of truth": "## OpenAPI as source of truth",
    "## Что проверять в contract-тесте": "## What to check in a contract test",
    "## Consumer vs provider (кратко)": "## Consumer vs provider (brief)",
    "## Что тестировать в UI vs unit": "## What to test in UI vs unit",
    "## Стабильные селекторы": "## Stable selectors",
    "## Ожидания без sleep": "## Expectations without sleep",
    "## Изоляция между тестами": "## Isolation between tests",
    "## Типичные антипаттерны": "## Typical anti-patterns",
    "## Цикл red – green – refactor": "## Red – green – refactor cycle",
    "## Что TDD не решает": "## What TDD does not solve",
    "## Мини-пример (Swift Testing)": "## Mini example (Swift Testing)",
    "## Типичное разделение": "## Typical split",
    "## Настройка в Xcode": "## Setup in Xcode",
    "## Связь с тегами Swift Testing": "## Link to Swift Testing tags",
    "## Выбор подхода": "## Choosing an approach",
    "## Что проверять в unit": "## What to check in unit tests",
    "## Дальше": "## Next",
    "## Пирамида тестирования": "## Testing pyramid",
    "## UI (опционально)": "## UI (optional)",
    "## Test Plan (конфигурация)": "## Test Plan (configuration)",
    "### Child topics (углубления)": "### Child topics (deep dives)",
    "### immh — Mobile System Design Interview (глава 1)": "### immh — Mobile System Design Interview (chapter 1)",
    "### Что такое mobile system design interview": "### What a mobile system design interview is",
    "### Отличие от backend / generic SD": "### Difference from backend / generic SD",
    "### Структура ответа (45 мин)": "### Answer structure (45 min)",
    "### Entity graph и потоки данных": "### Entity graph and data flows",
    "## Swift: базовый синтаксис и идиоматика — описание": "## Swift: basic syntax and idioms — overview",
    "## Типы, протоколы, дженерики, opaque и existentials — описание": "## Types, protocols, generics, opaque and existentials — overview",
    "## 📊 some vs any (интуиция)": "## 📊 some vs any (intuition)",
    "## Связка с карточками (Q&A) — defer, type methods, class init": "## Q-card tie-in — defer, type methods, class init",
    "### Сравниваем не «протокол против дженерика», а **`T: P`** vs **`any P`": "### Compare `T: P` vs `any P`, not protocol vs generic",
    "### `some P` (opaque) vs `any P` (existential) — коротко": "### `some P` (opaque) vs `any P` (existential) — brief",
    "### Dispatch и связь с `any` vs generic (что спрашивают Middle/Senior)": "### Dispatch and `any` vs generic (Middle/Senior)",
    "### Устные опоры (формат карточек)": "### Oral anchors (card format)",
    "### Почему у `class` нет memberwise `init`, как у `struct`": "### Why `class` has no memberwise `init` like `struct`",
    "### Optionals (связка с junior-линией)": "### Optionals (junior track tie-in)",
    "### Playgrounds под номера карточек (Q)": "### Playgrounds by Q-card number",
    "## Что было неудобно до SE-0508": "## What was awkward before SE-0508",
    "## Что меняется": "## What changes",
    "## Пример с Array-инициализатором": "## Example with Array initializer",
    "## Где особенно полезно": "## Where especially useful",
    "## Что важно понимать": "## What to understand",
    "## Конспект Senior: autorelease pool и ARC (тема **II·07**)": "## Senior notes: autorelease pool and ARC (topic **II·07**)",
    "## Доп. конспект: Avito ч.1 (теория)": "## Extra notes: Avito pt.1 (theory)",
    "### Области памяти": "### Memory regions",
    "### Экзистенциальный контейнер": "### Existential container",
    "### Типы ссылок (цена / безопасность)": "### Reference types (cost / safety)",
    "### Жизненный цикл объекта": "### Object lifecycle",
    "### Класс vs struct (критерии Apple)": "### Class vs struct (Apple criteria)",
    "### Non-frozen типы": "### Non-frozen types",
    "### Инструменты": "### Tools",
    "### Собес ~60 с: side table + жизненный цикл": "### ~60s interview: side table + lifecycle",
    "## Доп. конспект: Avito ч.2 (практика)": "## Extra notes: Avito pt.2 (practice)",
    "## 🌟 Strategic (Senior+) — командные практики": "## 🌟 Strategic (Senior+) — team practices",
    "## 1) Регистры процессора": "## 1) CPU registers",
    "## 2) Кэш-память (L1 / L2 / L3)": "## 2) Cache memory (L1 / L2 / L3)",
    "## 3) Оперативная память (RAM / ОЗУ)": "## 3) RAM",
    "## 4) Постоянная память (SSD / HDD / ПЗУ)": "## 4) Persistent storage (SSD / HDD)",
    "## 5) Виртуальная память": "## 5) Virtual memory",
    "## Почему это важно iOS-разработчику": "## Why this matters to iOS developers",
    "## Пример на практике (iOS)": "## Practical example (iOS)",
    "## Термины, которые часто спрашивают": "## Terms often asked in interviews",
    "### План миграции на strict concurrency (большой проект)": "### Strict concurrency migration plan (large project)",
    "### Архитектурные паттерны: `@MainActor-only` vs Domain actors": "### Architecture patterns: `@MainActor-only` vs domain actors",
    "### Обучение команды (enablement)": "### Team enablement",
    "## 1) Task как future/promise-контракт": "## 1) Task as future/promise contract",
    "## 2) Task как точка согласования": "## 2) Task as coordination point",
    "## 3) Task как вход в async из sync API": "## 3) Task as entry to async from sync API",
    "## 1) Командный контракт (code review rules)": "## 1) Team contract (code review rules)",
    "### Temporary allowed (только с тикетом и дедлайном)": "### Temporarily allowed (ticket + deadline only)",
    "## 2) Миграция: фазы, метрики, Definition of Done": "## 2) Migration: phases, metrics, Definition of Done",
    "### Фаза 0 — Инвентаризация": "### Phase 0 — Inventory",
    "### Фаза 1 — Async API на границах": "### Phase 1 — Async API at boundaries",
    "### Фаза 2 — Isolation domains": "### Phase 2 — Isolation domains",
    "### Фаза 3 — Strict concurrency (постепенно)": "### Phase 3 — Strict concurrency (gradual)",
    "### Метрики прогресса": "### Progress metrics",
    "### Definition of Done (для модуля)": "### Definition of Done (per module)",
    "## 3) Мини чеклист code review": "## 3) Mini code review checklist",
    "### Кратко: pattern → описание": "### Brief: pattern → description",
    "### Delegate (делегирование)": "### Delegate",
    "### DataSource (источник данных)": "### DataSource",
    "### Observer (наблюдатель)": "### Observer",
    "### Singleton (одиночка)": "### Singleton",
    "### Factory (фабрика)": "### Factory",
    "### Builder (строитель)": "### Builder",
    "### Coordinator (координатор)": "### Coordinator",
    "### Adapter (адаптер)": "### Adapter",
    "### Strategy (стратегия)": "### Strategy",
    "### Facade (фасад)": "### Facade",
    "### Dependency Injection (внедрение зависимостей)": "### Dependency Injection",
    "### Вопрос": "### Question",
    "### Ответ": "### Answer",
    "### Ментальная модель": "### Mental model",
    "### Пошагово": "### Step by step",
    "### Типичные ошибки": "### Typical mistakes",
    "### Если бы `Entity` был struct": "### If `Entity` were a struct",
    "### Follow-up на собесе": "### Interview follow-up",
    "### Два утверждения — не смешивать": "### Two claims — do not mix",
    "### Таймлайн": "### Timeline",
    "### Почему не другие варианты": "### Why not the other options",
    "### Как писать безопасно": "### How to write safely",
    "### Связь с GCD": "### Link to GCD",
    "### Память": "### Memory",
    "### Почему не остальные": "### Why not the others",
    "### Оговорки": "### Caveats",
    "### Типичный fix": "### Typical fix",
    "# SPM: Common → Services → Features (шпаргалка)": "# SPM: Common → Services → Features (cheatsheet)",
    "# Mobile System Design Interview — глава 1": "# Mobile System Design Interview — chapter 1",
    "# Snapshot testing — дисциплина": "# Snapshot testing — discipline",
    "# Contract tests и OpenAPI": "# Contract tests and OpenAPI",
    "# Unit-тесты на уровне Senior / Lead (iOS, Swift)": "# Senior / Lead unit tests (iOS, Swift)",
    "### Q1: Что такое metaprogramming в контексте Swift?": "### Q1: What is metaprogramming in Swift?",
    "### Q2: Что возвращает `Mirror(reflecting:)` и зачем `children`?": "### Q2: What does `Mirror(reflecting:)` return and why `children`?",
    "### Q3: Чем `Mirror` отличается от Objective-C runtime?": "### Q3: How is `Mirror` different from Objective-C runtime?",
    "### Q4: Почему computed property может отсутствовать в `children`?": "### Q4: Why can a computed property be missing from `children`?",
    "### Q5: Как работает `@dynamicMemberLookup`?": "### Q5: How does `@dynamicMemberLookup` work?",
    "### Q6: Mirror vs `Codable` для JSON?": "### Q6: Mirror vs `Codable` for JSON?",
    "### Q7: Когда `Mirror` уместен в production?": "### Q7: When is `Mirror` appropriate in production?",
    "### Q8: Риск `JSONObject` с silent null на missing key?": "### Q8: Risk of `JSONObject` silent null on missing key?",
    "### Q9: Что выбрать для remote config — dynamic или struct?": "### Q9: Remote config — dynamic or struct?",
    "### Q10: Runtime vs Swift macros — одна фраза?": "### Q10: Runtime vs Swift macros — one line?",
    "### Q: List мигает или сбрасывает state в строке после update / delete": "### Q: List flickers or resets row state after update / delete",
    "### Q: Когда `List`, когда `LazyVStack`?": "### Q: When `List`, when `LazyVStack`?",
    "### Q: `TimelineView` vs `Timer` — когда что?": "### Q: `TimelineView` vs `Timer` — when to use which?",
    "### Q: Почему не вызывать API в `.onAppear`?": "### Q: Why not call API in `.onAppear`?",
    "### Q1: Зачем enum, если remote config отдаёт строки?": "### Q1: Why enum when remote config returns strings?",
    "### Q2: Почему приоритеты, а не «последний write wins»?": "### Q2: Why priorities instead of last write wins?",
    "### Q3: NSLock vs actor для `FeatureFlags`?": "### Q3: NSLock vs actor for `FeatureFlags`?",
    "### Q4: Как тестировать?": "### Q4: How to test?",
    "### 1) Не использовать plan mode — ошибка": "### 1) Not using plan mode — mistake",
    "### 2) Воспринимать промпты как одноразовые — ошибка": "### 2) Treating prompts as one-shot — mistake",
    "### 3) Игнорировать skills — ошибка": "### 3) Ignoring skills — mistake",
    "### 4) Отдавать выбор модели полностью “авто” — риск": "### 4) Fully automatic model choice — risk",
    "### 5) Пытаться сделать всё одним большим промптом — ошибка": "### 5) One giant prompt for everything — mistake",
    "### 6) Поверхностно ревьюить изменения — прямой путь к техдолгу": "### 6) Shallow review — fast path to tech debt",
    "### 7) Не изучать инструменты глубоко — потеря leverage": "### 7) Not learning tools deeply — lost leverage",
    "### 8) Работать без hooks/rules/guardrails — ошибка": "### 8) Working without hooks/rules/guardrails — mistake",
    "### 9) Не развивать AGENTS/rules по итогам ошибок — ошибка": "### 9) Not evolving AGENTS/rules from mistakes — mistake",
    "### 10) Пропускать tests/CI в PR — ускоренный путь к регрессиям": "### 10) Skipping tests/CI in PR — fast regressions",
    "### 11) Избегать дискомфорта с новыми инструментами — ограничение роста": "### 11) Avoiding discomfort with new tools — limits growth",
    "## 1. Мутация через копию массива (class vs struct)": "## 1. Mutation via array copy (class vs struct)",
    "## 2. Actor reentrancy и `async let`": "## 2. Actor reentrancy and `async let`",
    "## 3. Производительность: 10 000 маленьких моделей — struct vs class в массиве": "## 3. Performance: 10,000 small models — struct vs class in array",
    "## 4. `@MainActor` и вызов из non-isolated `async`": "## 4. `@MainActor` and call from non-isolated `async`",
    "## 1. Что значит «писать тесты как сеньор»": "## 1. What “writing tests like a senior” means",
    "## 2. Пирамида и границы unit": "## 2. Pyramid and unit boundaries",
    "## 3. Словарь test doubles (как на собесе)": "## 3. Test doubles vocabulary (interview)",
    "## 4. XCTest и Swift Testing (кратко)": "## 4. XCTest and Swift Testing (brief)",
    "## 5. Асинхронность без флейков": "## 5. Async without flakes",
    "## 6. MainActor и UI-логика": "## 6. MainActor and UI logic",
    "## 7. Вопросы–ответы (собес / самопроверка)": "## 7. Interview Q&A (self-check)",
    "## 8. Задачки (сделай сам, без готового кода)": "## 8. Exercises (do yourself, no ready code)",
    "## 9. Мини-шаблоны (идеи кода, без комментариев внутри Swift)": "## 9. Mini templates (code ideas, no comments in Swift)",
    "## 10. Антипаттерны (частые причины провала на собесе)": "## 10. Anti-patterns (common interview failures)",
    "## 11. Чеклист ревью тестов (как лид)": "## 11. Test review checklist (as lead)",
    "## 12. Что читать дальше (официально)": "## 12. Read next (official)",
    "# TDD — основы (без AI)": "# TDD basics (without AI)",
    "# Test Plans и CI": "# Test Plans and CI",
    "# Unit-тесты сети без HTTP": "# Network unit tests without HTTP",
    "# Конспект по «Чертовски понятному Swift Concurrency» (RU-сайт)": "# Notes on Approachable Swift Concurrency (RU site)",
    "# Основы тестирования (интервью)": "# Testing fundamentals (interview)",
    "# Что значит «structured» в Structured Concurrency": "# What “structured” means in Structured Concurrency",
    "# Эволюция многопоточности на Apple-платформах: от потоков до Swift Concurrency": "# Concurrency evolution on Apple platforms: threads to Swift Concurrency",
    "## 1. Closures наследуют actor isolation": "## 1. Closures inherit actor isolation",
    "## 1. Зачем `async`/`await`": "## 1. Why `async`/`await`",
    "## 1. Процесс и поток ОС": "## 1. OS process and thread",
    "## 10. Сводная таблица": "## 10. Summary table",
    "## 10. Шпаргалка ключевых слов (как на сайте)": "## 10. Keyword cheat sheet (as on site)",
    "## 11. Куда дальше (ссылки с сайта)": "## 11. Where next (links from site)",
    "## 11. Ссылки": "## 11. Links",
    "## 2) Сжатие ответа: gzip vs Brotli": "## 2) Response compression: gzip vs Brotli",
    "## 2. `@MainActor` delegate methods с wrong thread": "## 2. `@MainActor` delegate methods on wrong thread",
    "## 2. `@globalActor` BackgroundActor — антипаттерн": "## 2. `@globalActor` BackgroundActor — anti-pattern",
    "## 2. `Task` и структура работы": "## 2. `Task` and work structure",
    "## 2. Явный поток: `Thread`": "## 2. Explicit thread: `Thread`",
    "## 3) Частичный рендеринг и предрасчёт layout": "## 3) Partial rendering and precomputed layout",
    "## 3. Custom executor actor (легитимный «stateless»)": "## 3. Custom executor actor (legitimate “stateless”)",
    "## 3. [RunLoop](../../../XI. Резюме/Глоссарий/Glossary.md#glossary-runloop) и один поток": "## 3. [RunLoop](../../../XI. Резюме/Глоссарий/Glossary.md#glossary-runloop) and one thread",
    "## 3. От потоков к изоляции": "## 3. From threads to isolation",
    "## 3. Прочие сценарии": "## 3. Other scenarios",
    "## 4. GCD: очереди и блоки": "## 4. GCD: queues and blocks",
    "## 4. Три домена изоляции (как на сайте)": "## 4. Three isolation domains (as on site)",
    "## 4. Файловая система = внешнее state": "## 4. File system = external state",
    "## 5. Approachable Concurrency и `@concurrent` (Swift 6.2+)": "## 5. Approachable Concurrency and `@concurrent` (Swift 6.2+)",
    "## 5. First rule of actors (для собеса)": "## 5. First rule of actors (interview)",
    "## 5. `Operation` и `OperationQueue`": "## 5. `Operation` and `OperationQueue`",
    "## 5. Что такое actor и какую проблему решает": "## 5. What an actor is and what problem it solves",
    "## 6. Callbacks и делегаты (без `async`)": "## 6. Callbacks and delegates (without `async`)",
    "## 7. Combine как слой поверх GCD": "## 7. Combine as a layer over GCD",
    "## 7. Быстрые ответы (flashcards)": "## 7. Quick answers (flashcards)",
    "## 7. Как «течёт» изоляция": "## 7. How isolation “leaks”",
    "## 8. Сводная модель (центральная мысль сайта)": "## 8. Summary model (central idea of site)",
    "## 9. Одна и та же задача: четыре эпохи": "## 9. Same task: four eras",
    "## 9. Типичные ошибки (чеклист с сайта)": "## 9. Typical mistakes (checklist from site)",
    "## Cancellation как практическое следствие": "## Cancellation as a practical consequence",
    "## Constraints-файл: правила, не документация": "## Constraints file: rules, not documentation",
    "## Crash symbols в отчёте": "## Crash symbols in report",
    "## Fake client (предпочтительно)": "## Fake client (preferred)",
    "## Flaky tests в CI": "## Flaky tests in CI",
    "## LLM и TDD: разные оптимизации": "## LLM and TDD: different optimizations",
    "## Launch arguments и тестовый режим": "## Launch arguments and test mode",
    "## Swift 5 vs Swift 6 (одной строкой)": "## Swift 5 vs Swift 6 (one line)",
    "## Test doubles — самое важное для интервью": "## Test doubles — most important for interviews",
    "## URLProtocol stub (кратко)": "## URLProtocol stub (brief)",
    "## `async let` с отброшенным результатом": "## `async let` with discarded result",
    "## Связка с карточками (Q&A) — `any` vs generics, `associatedtype`, dispatch": "## Q-card tie-in — `any` vs generics, `associatedtype`, dispatch",
    "### Structured — дерево": "### Structured — tree",
    "### TaskGroup — structured, несмотря на имя «Task»": "### TaskGroup — structured, despite the name “Task”",
    "### Unstructured — плоский список": "### Unstructured — flat list",
    "### Главная мысль": "### Main idea",
    "### Инструкции для ассистента": "### Instructions for assistant",
    "### Контракт и контроль": "### Contract and control",
    "### Краткий ответ (1–2 предложения)": "### Short answer (1–2 sentences)",
    "### Мини-примеры (Swift)": "### Mini examples (Swift)",
    "### Развёрнуто": "### In depth",
    "### Связь с другими материалами": "### Link to other materials",
    "### Сравнение с предшественниками": "### Comparison with predecessors",
    "### Сравниваем не «протокол против дженерика», а **`T: P`** vs **`any P`": "### Compare `T: P` vs `any P`, not protocol vs generic",
    "### Эволюция, не цемент": "### Evolution, not cement",
    "## 3. [RunLoop](../../../glossary/README.md#glossary-runloop) and one thread": "## 3. [RunLoop](../../../glossary/README.md#glossary-runloop) and one thread",
}


def iter_md_files() -> list[Path]:
    paths: list[Path] = []
    for md in KB.rglob("*.md"):
        rel = md.relative_to(KB).as_posix()
        if any(part in SKIP_DIRS for part in rel.split("/")):
            continue
        paths.append(md)
    return sorted(paths)


def translate_line(line: str) -> str:
    stripped = line.rstrip("\n")
    if stripped in REPLACEMENTS:
        return REPLACEMENTS[stripped] + ("\n" if line.endswith("\n") else "")
    m = HEADING_LINE.match(stripped)
    if not m or not CYRILLIC.search(m.group(2)):
        return line
    return line


def migrate_file(path: Path, dry_run: bool = False) -> int:
    original = path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)
    changed = 0
    out: list[str] = []
    for line in lines:
        new_line = translate_line(line)
        if new_line != line:
            changed += 1
        out.append(new_line)
    if changed and not dry_run:
        path.write_text("".join(out), encoding="utf-8")
    return changed


def remaining_cyrillic_headings() -> list[str]:
    found: set[str] = set()
    for path in iter_md_files():
        for line in path.read_text(encoding="utf-8").splitlines():
            m = HEADING_LINE.match(line)
            if m and CYRILLIC.search(m.group(2)):
                found.add(line.strip())
    return sorted(found)


def main() -> int:
    dry = "--dry-run" in sys.argv
    total_files = 0
    total_lines = 0
    for path in iter_md_files():
        n = migrate_file(path, dry_run=dry)
        if n:
            total_files += 1
            total_lines += n
            print(f"{path.relative_to(KB)}: {n}")
    print(f"\n{'Would change' if dry else 'Changed'} {total_lines} heading(s) in {total_files} file(s)")
    left = remaining_cyrillic_headings()
    if left:
        print(f"\nRemaining Cyrillic headings ({len(left)}):")
        for h in left:
            print(f"  {h}")
        return 1
    print("\nNo Cyrillic headings remaining.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
